config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'
  get 'projects' => 'static_pages#projects'
  get 'contact' => 'contacts#new'
  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def index
		@contact = Contact.all
	end

	def create
		@contact = Contact.new(user_params)
		@contact.save
		if @contact.save
			flash[:success] = "Your message has been sent."
			UserMailer.contact(@contact).deliver
			redirect_to root_path
		else
			render 'contact'
		end
	end

	def new
		@contact = Contact.new
	end

	private
	def user_params
		params.require(:contact).permit(:email, :message)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def projects
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/index.html.erb
<div class="page-header">
  <h1>Conctact Queries</h1>
</div>

<% @contact.each do |c| %>
	<div class = "row">
		<div class = "col-md-6 col-md-offset-3">
			<ul>
				<li><%= c.message %> ( <%= c.email %> )</li>
			</ul>
		</div>
	</div>
<% end %>

app/views/contacts/new.html.erb
<div class="page-header">
  <h1>Contact</h1>
</div>

<div class = "row">
	<div class = "col-md-6 col-md-offset-3">
		<%= form_for(@contact) do |f| %>
			<%= f.label :email %>
			<%= f.text_field :email %><br>

			<%= f.label :message %>
			<%= f.text_area :message, class: "contact_message_box" %>

			<%= f.submit :submit, class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div id="footer" class="container">
	<div class="container">
		<p class="text-muted">&copy; Rajan Gupta</p>
	</div>
</div>

app/views/layouts/_gAnalytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-57272531-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<%= link_to "RG", root_path, class: "navbar-brand" %>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    	<ul class="nav navbar-nav navbar-right">
	    		<li class = <%= (action_name == "home") && (controller_name == "static_pages") ? "active" : "" %> ><%= link_to "Home", root_path %></li>
	      		<li class = <%= (action_name == "projects") && (controller_name == "static_pages") ? "active" : "" %> ><%= link_to "Projects", projects_path %></li>
	      		<li class = <%= (action_name == "new") && (controller_name == "contacts") ? "active" : "" %> ><%= link_to "Contact", contact_url %></li>
	      	</ul>
    	</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Rajanjamu</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<%= yield %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development? %>
	<%= render 'layouts/gAnalytics' %>
</body>
</html>

app/views/static_pages/home.html.erb
<div class="page-header">
  <h1>Rajanjamu <small>personal website</small></h1>
</div>

<div id="content">
	<p >
		Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	</p>
</div>
	

app/views/static_pages/projects.html.erb
<div class="page-header">
  <h1>Projects</h1>
</div>